### ISSUE TITLE
コードオブコンダクト制定

### ISSUE THREAD

**Issue by sinmetal** [gcpug/dogrun#1]
コードオブコンダクト (行動規範) を作成する。
最初に利用する予定は、dogrunのイベントだが、そのままGCPUGのコードオブコンダクト (行動規範) として、採用できると嬉しい。

**Comment by kuma** [comment]
一応禁止事項は gcpug.jp にまとまってるんだな

禁止事項
GCPUGはGCPのナレッジの共有を目的としたコミュニティです。

他社批判をしない（比較はWelcome）
お金儲けに使わない
誹謗中傷をしない
迷惑行為をしない
内輪ネタにしない
来るものを拒まない
押し売りをしない

**Comment by sinmetal** [comment]
Cloud Nextのやつ

Google is dedicated to providing a harassment-free and inclusive event experience for everyone regardless of gender identity and expression, sexual orientation, disabilities, neurodiversity, physical appearance, body size, ethnicity, nationality, race, age, religion, or other protected categories. We do not tolerate harassment of event participants in any form. Google takes violations of our policy seriously and will respond appropriately. For more information, go to [Google’s Event Community Guidelines and Anti-Harassment Policy](https://www.google.com/events/policy/anti-harassmentpolicy.html) .

**Comment by tenntenn** [comment]
https://docs.google.com/document/d/1-SvKYYs5Qy9avXx2Z_-9Kfahheq0A2IIAxdD45-WWzI
https://docs.google.com/document/d/1IAVntx7oXckRzhlHu-6JVrJIyxpmxjaMIYJSl3mcJ1c

**Comment by sinmetal** [comment]
WebSiteにいい感じに載せねばな

**Comment by sinmetal** [comment]
done. https://github.com/sinmetal/dogrun/pull/17
