### ISSUE TITLE
I want you to be able to set not null (+ default value) when adding a column

### ISSUE THREAD

**Issue by s-arai-games** [gcpug/dogrun#11]
カラム追加時にnot null(+default value)を設定できるようにしてほしい

# WHAT
テーブルへのカラム追加時にnot null(+default value)を設定できるようにしてほしい

# WHY
アプリケーションの開発・運用ではカラムの追加が頻繁に起こるので、default値が設定できると大変ありがたい。
また一般的なRDBMSでは、即時反映ではないがnot null(+default value)のカラム追加が可能である。
RDBMSとNoSQLの両立を目指すCloud Spannerでは是非いつか対応してほしい。

【以下はこちらの想像】
Spannerのカラム追加とは、実データの操作をせずにカラムが存在しているというフラグを立てるのみで、アクセスしたときに評価を行ってkeyに紐づくそのカラムの値が無ければnullを返すようにしていると思う。（そしてupdateの際にカラムに値が指定されれば、そのとき初めて実際に値が入る）
そう考えると、keyに紐づくそのカラムの値が無ければdefault値を返すように出来るんじゃないかと勝手に想像している。
Cloud Spannerのinformation_schemaを取得するとCOLUMN_DEFAULTなる予約領域のようなものが既に存在しているので、少し期待している

**Comment by s-arai-games** [comment]
こちらは、CloudSpannerについての要望になります。

**Comment by sinmetal** [comment]
# Ask

頑張ってるよ！
