### ISSUE TITLE
I would like to use Firestore Native Mode and Datastore Mode in the same Project

### ISSUE THREAD

**Issue by sinmetal** [gcpug/dogrun#2]
# WHAT

同じProjectで、Firestore Native ModeとDatastore Modeを利用したい。

# WHY

mBaaSとしてエンドユーザに提供する機能と、裏側で分析などに利用する機能がある場合、Firestore Native Mode, Datastore Mode 両方を使いたい。

**Comment by kuma** [comment]
I would like to use Firestore Native Mode and Datastore Mode in the same Project
だな

**Comment by sinmetal** [comment]
# Ask

元々はあまりユースケースとしては想定していなかったけど、ニーズがあることが分かった。
現状では複数プロジェクトを作成すれば、可能だ。
