### ISSUE TITLE
Next昼のブースのLink共有

### ISSUE THREAD

**Issue by sinmetal** [gcpug/dogrun#29]
https://docs.google.com/presentation/d/e/2PACX-1vSswu7S1LQO9dkA6vkLutYD2U8J-ch3lkPz_53W3rQGA38XHJRHF9ShVXk8Z1UvrXfWO99tOKUZZWl0/pub?start=true&loop=true&delayms=30000&slide=id.g3f4bdd67d5_0_0

**Comment by tenntenn** [comment]
https://docs.google.com/presentation/d/e/2PACX-1vRgy3u5g-4zWIU1HXbtGHvivTWMkOll2nbbrwUPirLMpMAYdUzpXvGFZ5m8MYhoPgJYub4jwfT4ZRlc/pub?start=true&loop=true&delayms=5000
