### ISSUE TITLE
Is there going to be a difference of performance between Firestore Datastore Mode and legacy Cloud Datastore?

### ISSUE THREAD

**Issue by sinmetal** [gcpug/dogrun#6]
Firestore : Datastore Mode は既存のDatastoreとパフォーマンスは変わる？

# WHAT

Everything became Strong Consistency in Firestore Datastore Mode, so is there going to be performance difference? In the Documentation states "Not yet fully optimized; may experience increased latency during beta", so when it comes to GA, performance will change?
As people who is using legacy Cloud Datastore users, is there something to consider in terms of performance difference?

すべてがStrong Consistencyになったことで、既存のDatastoreよりパフォーマンスが落ちたりするのだろうか？
ドキュメントには以下のように書いてあるけど、GAになるとパフォーマンスが変わったりする？

```
Not yet fully optimized; may experience increased latency during beta
```

# WHY

既存のDatastoreを使っている人たちは、パフォーマンスのために何か考えることはあるのだろうか？

**Comment by kuma** [comment]
Is there going to be a difference of performance between Firestore Datastore Mode and legacy Cloud Datastore?   
Everything became Strong Consistency in Firestore Datastore Mode, so is there going to be performance difference? In the Documentation states "Not yet fully optimized; may experience increased latency during beta", so when it comes to GA, performance will change?   
As people who is using legacy Cloud Datastore users, is there something to consider in terms of performance difference?

**Comment by apstndb** [comment]
補足して聞きたいこととしては、
そもそも Cloud Firestore 両方とも制約については書かれていてもパフォーマンス特性として参考にするドキュメントがないから、下記のようなパフォーマンスに関するベストプラクティスみたいなものは書かれるのかどうかが気になりました。
https://cloud.google.com/datastore/docs/best-practices

`Are you planning to write the article about performance considerations of Cloud Firestore?` とかで独立の issue にするか悩むところ。

**Comment by sinmetal** [comment]
別個のリクエストにしても別にいいんじゃないかな？
去年も、Spannerのテーブル設計についてのドキュメントが欲しいみたいな要望があったような気がする。

**Comment by sinmetal** [comment]
# Ask

パフォーマンスについては変わらないように注意してみている。
実際にプロダクションのデータをミラーリングして、パフォーマンスをモニタリングしている。
そのため、ほとんどのユースケースでは問題がないはずだ。
ただ、1Txで3000Index更新したりするようなレアケースではパフォーマンスに問題が発生するかもしれない。
