### ISSUE TITLE
I want the ability to put Spanner's change event in PubSub

### ISSUE THREAD

**Issue by sinmetal** [gcpug/dogrun#7]
As a user, I want to have a publisher in Spanner that would publish updated data in Spanner, like BINLOG in MySQL, to Pub/Sub. So that I can make a trigger for that.

# WHAT

MySQLのBINLOGみたいなのをPubSubにぶっこむ機能が欲しい

# WHY

変更をトリガーしたい

**Comment by kuma** [comment]
変更をトリガーにしたい、、だよな。

**Comment by kuma** [comment]
As a user, I want to have a publisher in Spanner that would publish updated data in Spanner, like BINLOG in MySQL, to Pub/Sub.  So that I can make a trigger for that.

**Comment by kuma** [comment]
なんかすっごい英語が出てこなかった。

**Comment by sinmetal** [comment]
# Ask

要望があることは認識している。
現時点では、CommitTimestampをアプリケーションでWatchして、自分でPubSubに入れるというような方法を取ることになる。

# Q : FirestoreはSpannerを使っている？

# A

Spannerのテクノロジーを利用しているが、いろんなコンポーネントが存在する。
